#!/usr/bin/env python3
"""Signal Growth Engine pipeline helper.

This replaces the old one-off video script with a small, durable command runner:
research/script assets live in files, Veo creates clips, ElevenLabs creates Abby VO,
ffmpeg assembles, and Codex approval remains the only publish gate.
"""

from __future__ import annotations

import argparse
import base64
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
MARKETING_DIR = ROOT / "marketing"
RUNS_DIR = MARKETING_DIR / "growth_runs"
DB_PATH = MARKETING_DIR / "signal_growth_engine.sqlite"
SKILLS_DIR = ROOT / "skills"
ASSEMBLE_PS1 = SKILLS_DIR / "assemble.ps1"

ABBY_VOICE_ID = "lkFHOvhI41u53xDdGZoZ"
DEFAULT_VEO_MODEL = "veo-3.1-lite-generate-preview"

OVERLAY_CANVAS = (1080, 1920)

STATUS_ORDER = {
    "QUEUED",
    "RESEARCHED",
    "SCRIPTED",
    "VOICED",
    "VIDEO_GENERATED",
    "RENDERED",
    "QA_PASSED",
    "AWAITING_CODEX_APPROVAL",
    "APPROVED",
    "REJECTED",
    "REVISION_REQUESTED",
    "PUBLISHED",
    "MEASURED",
    "FAILED",
}


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        # The project .env is the source of truth for this pipeline. This avoids
        # stale shell-level keys from older projects silently taking priority.
        os.environ[key] = value


def load_env() -> None:
    load_env_file(ROOT / ".env")
    load_env_file(Path(__file__).resolve().parent / ".env")


def db() -> sqlite3.Connection:
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS video_runs (
            id TEXT PRIMARY KEY,
            topic TEXT NOT NULL,
            title TEXT,
            status TEXT NOT NULL,
            landing_url TEXT,
            utm_source TEXT,
            utm_content TEXT,
            video_path TEXT,
            audio_path TEXT,
            alignment_path TEXT,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            qa_json TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS video_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            run_id TEXT NOT NULL,
            event_type TEXT NOT NULL,
            payload_json TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL
        )
        """
    )
    conn.commit()
    return conn


def emit(obj: dict[str, Any]) -> None:
    print(json.dumps(obj, indent=2, ensure_ascii=True))


def run_folder(run_id: str) -> Path:
    folder = RUNS_DIR / run_id
    folder.mkdir(parents=True, exist_ok=True)
    return folder


def scaffold_run_files(folder: Path, title: str, topic: str) -> None:
    files = {
        "research.md": f"# Research\n\nTopic: {topic}\n\n- Winning angle 1:\n- Winning angle 2:\n- Winning angle 3:\n",
        "script.md": (
            f"# Script: {title}\n\n"
            "Hook:\n\n"
            "Beats:\n\n"
            "CTA: Need yours fixed? Link in bio.\n"
        ),
        "shot01.txt": (
            "Vertical 9:16 short-form video shot. Use the active Signal/Veo prompt template. "
            "No on-screen text generated by the model. Keep the artifact readable and the movement motivated."
        ),
        "vo_hook.txt": "This resume looks fine, and that is exactly why the mistake is easy to miss.",
        "vo_search.txt": (
            "If the job asks for specific tools, your resume needs proof in that language. "
            "Otherwise a recruiter search can miss you."
        ),
        "vo_demo.txt": "The fix is not fake experience. It is saying the real work in the language of the job.",
        "vo_cta.txt": "Need yours fixed before you apply? The link is in my bio.",
    }
    for name, content in files.items():
        target = folder / name
        if not target.exists():
            target.write_text(content, encoding="utf-8")


def create_run(args: argparse.Namespace) -> None:
    conn = db()
    run_id = f"{datetime.now().strftime('%Y%m%d-%H%M')}-{uuid.uuid4().hex[:8]}"
    title = args.title or args.topic
    landing_url = args.landing_url or "https://ats-hacker-swart.vercel.app/?utm_source=codex&utm_medium=short&utm_campaign=signal_growth"
    now = utc_now()
    metadata = {
        "platforms": ["youtube_shorts", "tiktok", "instagram_reels"],
        "reviewRequired": True,
        "approvalPhrase": f"APPROVE POST {run_id}",
        "codexOnlyApproval": True,
        "publishBlockedUntilApproval": True,
    }
    conn.execute(
        """
        INSERT INTO video_runs (
          id, topic, title, status, landing_url, utm_source, utm_content,
          metadata_json, created_at, updated_at
        ) VALUES (?, ?, ?, 'QUEUED', ?, 'codex', ?, ?, ?, ?)
        """,
        (run_id, args.topic, title, landing_url, run_id, json.dumps(metadata), now, now),
    )
    log_event(conn, run_id, "created", metadata)
    conn.commit()
    folder = run_folder(run_id)
    (folder / "README.md").write_text(
        f"# {title}\n\nStatus: QUEUED\n\nApproval phrase: `APPROVE POST {run_id}`\n",
        encoding="utf-8",
    )
    scaffold_run_files(folder, title, args.topic)
    emit({"runId": run_id, "status": "QUEUED", "folder": str(folder), "approvalPhrase": metadata["approvalPhrase"]})


def get_run(conn: sqlite3.Connection, run_id: str) -> sqlite3.Row:
    row = conn.execute("SELECT * FROM video_runs WHERE id = ?", (run_id,)).fetchone()
    if not row:
        raise SystemExit(f"Unknown run id: {run_id}")
    return row


def log_event(conn: sqlite3.Connection, run_id: str, event_type: str, payload: dict[str, Any]) -> None:
    conn.execute(
        "INSERT INTO video_events (run_id, event_type, payload_json, created_at) VALUES (?, ?, ?, ?)",
        (run_id, event_type, json.dumps(payload), utc_now()),
    )


def update_run(conn: sqlite3.Connection, run_id: str, **fields: Any) -> None:
    if "status" in fields and fields["status"] not in STATUS_ORDER:
        raise SystemExit(f"Invalid status: {fields['status']}")
    fields["updated_at"] = utc_now()
    assignments = ", ".join(f"{key}=?" for key in fields)
    conn.execute(f"UPDATE video_runs SET {assignments} WHERE id=?", (*fields.values(), run_id))


def read_text_arg(args: argparse.Namespace) -> str:
    if getattr(args, "text", None):
        return args.text
    if getattr(args, "text_file", None):
        return Path(args.text_file).read_text(encoding="utf-8").strip()
    raise SystemExit("Provide --text or --text-file")


def elevenlabs_key() -> str:
    key = os.getenv("ELEVENLABS_API_KEY", "").strip()
    if not key or key.startswith("sk_your_"):
        raise SystemExit("ELEVENLABS_API_KEY is missing. Add it to marketing_agent/.env.")
    return key


def abby_voice_id() -> str:
    return (
        os.getenv("ELEVENLABS_ABBY_VOICE_ID")
        or os.getenv("ELEVENLABS_VOICE_ID")
        or ABBY_VOICE_ID
    ).strip()


def resolve_abby(args: argparse.Namespace) -> None:
    load_env()
    configured = abby_voice_id()
    key = os.getenv("ELEVENLABS_API_KEY", "").strip()
    if key and not key.startswith("sk_your_"):
        response = requests.get(
            "https://api.elevenlabs.io/v1/voices",
            headers={"xi-api-key": key},
            timeout=30,
        )
        if response.ok:
            voices = response.json().get("voices", [])
            for voice in voices:
                if voice.get("name", "").strip().lower() == "abby":
                    emit({"voice": "Abby", "voiceId": voice.get("voice_id"), "source": "elevenlabs"})
                    return
        if args.strict:
            raise SystemExit(f"Could not read Abby voice from ElevenLabs: {response.status_code} {response.text[:200]}")
    emit({"voice": "Abby", "voiceId": configured, "source": "configured"})


def seconds_from_alignment_value(value: float) -> float:
    return value / 1000 if value > 100 else value


def normalize_alignment(alignment: dict[str, Any]) -> dict[str, Any]:
    source = alignment.get("normalized_alignment") or alignment.get("alignment") or alignment
    chars = source.get("characters") or source.get("chars") or []
    starts = source.get("character_start_times_seconds") or source.get("character_start_times_ms") or []
    ends = source.get("character_end_times_seconds") or []
    durations = source.get("character_durations_seconds") or source.get("character_durations_ms") or []
    if not chars or not starts:
        return {"words": [], "raw": alignment}

    starts = [seconds_from_alignment_value(float(v)) for v in starts]
    if ends:
        ends = [seconds_from_alignment_value(float(v)) for v in ends]
    elif durations:
        durations = [seconds_from_alignment_value(float(v)) for v in durations]
        ends = [start + duration for start, duration in zip(starts, durations)]
    else:
        ends = starts[1:] + [starts[-1] + 0.08]

    words: list[dict[str, Any]] = []
    current: list[str] = []
    word_start: float | None = None
    word_end: float | None = None

    for char, start, end in zip(chars, starts, ends):
        if str(char).isspace():
            if current and word_start is not None and word_end is not None:
                words.append({"word": "".join(current), "startSec": round(word_start, 3), "endSec": round(word_end, 3)})
            current = []
            word_start = None
            word_end = None
            continue
        if word_start is None:
            word_start = start
        current.append(str(char))
        word_end = end

    if current and word_start is not None and word_end is not None:
        words.append({"word": "".join(current), "startSec": round(word_start, 3), "endSec": round(word_end, 3)})

    return {"words": words, "raw": alignment}


def generate_voice(args: argparse.Namespace) -> None:
    load_env()
    text = read_text_arg(args)
    output = Path(args.out).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    voice_id = args.voice_id or abby_voice_id()
    model_id = args.model_id or os.getenv("ELEVENLABS_MODEL_ID", "eleven_multilingual_v2")
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}/with-timestamps"
    payload = {
        "text": text,
        "model_id": model_id,
        "voice_settings": {
            "stability": args.stability,
            "similarity_boost": args.similarity,
            "style": args.style,
            "use_speaker_boost": True,
        },
    }
    response = requests.post(
        url,
        headers={"xi-api-key": elevenlabs_key(), "Content-Type": "application/json"},
        json=payload,
        timeout=120,
    )
    if not response.ok:
        raise SystemExit(f"ElevenLabs voice generation failed: {response.status_code} {response.text[:500]}")
    data = response.json()
    audio_base64 = data.get("audio_base64")
    if not audio_base64:
        raise SystemExit("ElevenLabs response did not include audio_base64.")
    output.write_bytes(base64.b64decode(audio_base64))
    alignment_path = output.with_suffix(output.suffix + ".alignment.json")
    alignment_path.write_text(json.dumps(normalize_alignment(data), indent=2), encoding="utf-8")

    if args.run_id:
        conn = db()
        get_run(conn, args.run_id)
        update_run(conn, args.run_id, status="VOICED", audio_path=str(output), alignment_path=str(alignment_path))
        log_event(conn, args.run_id, "voiced", {"audioPath": str(output), "alignmentPath": str(alignment_path), "voiceId": voice_id})
        conn.commit()

    emit({"status": "VOICED", "voiceId": voice_id, "audio": str(output), "alignment": str(alignment_path)})


def gemini_key() -> str:
    key = (os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY") or "").strip()
    if not key:
        raise SystemExit("GOOGLE_API_KEY or GEMINI_API_KEY is missing. Add it to marketing_agent/.env.")
    return key


def generate_veo(args: argparse.Namespace) -> None:
    load_env()
    prompt = read_text_arg(args)
    output = Path(args.out).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    model = args.model or os.getenv("GEMINI_VEO_MODEL", DEFAULT_VEO_MODEL)
    base_url = "https://generativelanguage.googleapis.com/v1beta"
    request_body: dict[str, Any] = {
        "instances": [{"prompt": prompt}],
        "parameters": {"aspectRatio": args.aspect_ratio},
    }
    if args.dry_run:
        emit({"dryRun": True, "model": model, "request": request_body, "out": str(output)})
        return

    response = requests.post(
        f"{base_url}/models/{model}:predictLongRunning",
        headers={"x-goog-api-key": gemini_key(), "Content-Type": "application/json"},
        json=request_body,
        timeout=60,
    )
    if not response.ok:
        raise SystemExit(f"Veo request failed: {response.status_code} {response.text[:500]}")
    operation_name = response.json().get("name")
    if not operation_name:
        raise SystemExit(f"Veo response did not include operation name: {response.text[:500]}")

    deadline = time.time() + args.timeout_sec
    status: dict[str, Any] = {}
    while time.time() < deadline:
        status_response = requests.get(
            f"{base_url}/{operation_name}",
            headers={"x-goog-api-key": gemini_key()},
            timeout=60,
        )
        if not status_response.ok:
            raise SystemExit(f"Veo polling failed: {status_response.status_code} {status_response.text[:500]}")
        status = status_response.json()
        if status.get("done"):
            break
        time.sleep(args.poll_sec)
    if not status.get("done"):
        raise SystemExit(f"Veo generation timed out after {args.timeout_sec}s: {operation_name}")

    try:
        uri = status["response"]["generateVideoResponse"]["generatedSamples"][0]["video"]["uri"]
    except (KeyError, IndexError, TypeError) as exc:
        raise SystemExit(f"Veo operation completed without a video URI: {json.dumps(status)[:1000]}") from exc

    download = requests.get(uri, headers={"x-goog-api-key": gemini_key()}, timeout=180)
    if not download.ok:
        raise SystemExit(f"Veo download failed: {download.status_code} {download.text[:500]}")
    output.write_bytes(download.content)

    if args.run_id:
        conn = db()
        get_run(conn, args.run_id)
        metadata = json.loads(get_run(conn, args.run_id)["metadata_json"] or "{}")
        metadata.setdefault("veoClips", []).append({"path": str(output), "model": model, "prompt": prompt[:500]})
        update_run(conn, args.run_id, status="VIDEO_GENERATED", metadata_json=json.dumps(metadata))
        log_event(conn, args.run_id, "veo_generated", {"videoPath": str(output), "model": model})
        conn.commit()

    emit({"status": "VIDEO_GENERATED", "video": str(output), "operation": operation_name})


def font(name: str, size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        Path(os.environ.get("WINDIR", "C:/Windows")) / "Fonts" / name,
        Path("C:/Windows/Fonts") / name,
    ]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size=size)
    return ImageFont.load_default()


def wrapped_lines(draw: ImageDraw.ImageDraw, text: str, font_obj: ImageFont.ImageFont, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        trial = f"{current} {word}".strip()
        if draw.textbbox((0, 0), trial, font=font_obj)[2] <= width or not current:
            current = trial
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def rounded_rect(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], radius: int, fill: tuple[int, int, int, int], outline: tuple[int, int, int, int] | None = None, width: int = 1) -> None:
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline, width=width)


def draw_resume_base(draw: ImageDraw.ImageDraw) -> dict[str, tuple[int, int, int, int]]:
    paper = (152, 300, 928, 1420)
    shadow = (paper[0] + 16, paper[1] + 18, paper[2] + 16, paper[3] + 18)
    rounded_rect(draw, shadow, 28, (0, 0, 0, 72))
    rounded_rect(draw, (paper[0] - 18, paper[1] - 22, paper[2] + 18, paper[3] + 22), 34, (18, 24, 31, 220), (255, 255, 255, 48), 2)
    rounded_rect(draw, paper, 18, (252, 252, 247, 248), (20, 27, 38, 70), 2)

    title = font("segoeuib.ttf", 36)
    subtitle = font("segoeui.ttf", 17)
    section = font("segoeuib.ttf", 16)
    role = font("segoeuib.ttf", 20)
    body = font("segoeui.ttf", 18)
    small = font("segoeui.ttf", 15)
    tiny = font("segoeui.ttf", 14)
    mono = font("consola.ttf", 14)

    x = paper[0] + 56
    y = paper[1] + 48
    draw.text((x, y), "SHAWN MARTIN", font=title, fill=(15, 23, 42, 255))
    draw.text((x, y + 44), "Network Support Specialist  |  Austin, TX  |  shawn.m@example.com  |  linkedin.com/in/shawnmartin", font=subtitle, fill=(72, 84, 104, 255))
    draw.line((x, y + 78, paper[2] - 56, y + 78), fill=(20, 27, 38, 80), width=2)

    y += 105
    draw.text((x, y), "PROFESSIONAL SUMMARY", font=section, fill=(9, 102, 93, 255))
    y += 27
    summary = "Network support specialist with 4+ years supporting hybrid offices, user access, endpoint deployment, and recurring incident triage across healthcare and logistics teams."
    for line in wrapped_lines(draw, summary, small, paper[2] - 112 - x):
        draw.text((x, y), line, font=small, fill=(31, 41, 55, 255))
        y += 22

    y += 20
    draw.text((x, y), "TECHNICAL SKILLS", font=section, fill=(9, 102, 93, 255))
    y += 28
    skill_rows = [
        ("Networking", "TCP/IP, DNS, DHCP, VLANs, VPN access, Wi-Fi troubleshooting"),
        ("Platforms", "Windows 10/11, Microsoft 365, Azure AD, ServiceNow, Intune, Jamf"),
        ("Hardware", "Cisco switches, Meraki APs, laptops, printers, conference rooms"),
        ("Reporting", "ticket trends, root-cause notes, knowledge base articles, SLA follow-up"),
    ]
    for label, value in skill_rows:
        draw.text((x, y), label + ":", font=font("segoeuib.ttf", 14), fill=(15, 23, 42, 255))
        draw.text((x + 118, y), value, font=tiny, fill=(55, 65, 81, 255))
        y += 22

    y += 20
    draw.text((x, y), "EXPERIENCE", font=section, fill=(9, 102, 93, 255))
    y += 30
    draw.text((x, y), "IT Support Analyst  |  Northstar Health Systems", font=role, fill=(15, 23, 42, 255))
    draw.text((paper[2] - 230, y + 3), "2022 - Present", font=small, fill=(72, 84, 104, 255))
    y += 36

    bullets = [
        "Handled network issues for internal users across four office locations.",
        "Closed 35-50 weekly tickets covering VPN access, device setup, account lockouts, printer failures, and conference-room support.",
        "Partnered with infrastructure team to document recurring Wi-Fi drops and reduce repeat tickets by 18% over two quarters.",
        "Configured onboarding access for 120+ employees across Microsoft 365, Azure AD groups, and ServiceNow requests.",
        "Updated 24 knowledge-base articles so night-shift technicians could resolve repeat VPN and printer issues without escalation.",
    ]
    boxes: dict[str, tuple[int, int, int, int]] = {}
    for idx, bullet in enumerate(bullets):
        bullet_y = y
        draw.text((x + 4, bullet_y + 2), u"\u2022", font=body, fill=(15, 23, 42, 255))
        line_x = x + 34
        lines = wrapped_lines(draw, bullet, body, paper[2] - 92 - line_x)
        for line_index, line in enumerate(lines):
            draw.text((line_x, bullet_y + line_index * 25), line, font=body, fill=(15, 23, 42, 255))
        box_h = max(30, len(lines) * 25)
        if idx == 0:
            boxes["weak_bullet"] = (line_x - 10, bullet_y - 8, paper[2] - 66, bullet_y + box_h + 6)
        y += box_h + 15

    y += 10
    draw.text((x, y), "Desktop Support Technician  |  Lakeside Logistics", font=role, fill=(15, 23, 42, 255))
    draw.text((paper[2] - 230, y + 3), "2020 - 2022", font=small, fill=(72, 84, 104, 255))
    y += 34
    earlier_bullets = [
        "Imaged and deployed 180+ Windows laptops during warehouse device refresh.",
        "Tracked recurring scanner, printer, and Wi-Fi issues in ServiceNow for operations managers.",
    ]
    for bullet in earlier_bullets:
        draw.text((x + 4, y + 2), u"\u2022", font=body, fill=(15, 23, 42, 255))
        for line in wrapped_lines(draw, bullet, small, paper[2] - 145 - x):
            draw.text((x + 34, y), line, font=small, fill=(31, 41, 55, 255))
            y += 22
        y += 8

    y += 14
    draw.text((x, y), "NETWORK PROJECTS", font=section, fill=(9, 102, 93, 255))
    y += 28
    projects = [
        "VPN migration support: validated user access, documented common failures, and escalated firewall-rule gaps.",
        "Office refresh: imaged 80+ laptops, mapped printers, and tested switch ports before go-live.",
    ]
    for project in projects:
        draw.text((x + 4, y + 2), u"\u2022", font=body, fill=(15, 23, 42, 255))
        for line in wrapped_lines(draw, project, small, paper[2] - 145 - x):
            draw.text((x + 34, y), line, font=small, fill=(31, 41, 55, 255))
            y += 22
        y += 8

    y += 10
    draw.text((x, y), "CERTIFICATIONS", font=section, fill=(9, 102, 93, 255))
    y += 28
    draw.text((x, y), "CompTIA Network+ (2023)  |  Google IT Support Certificate  |  Cisco Networking Basics", font=small, fill=(31, 41, 55, 255))

    y += 40
    chip_x = paper[0] + 56
    for skill in ["Windows", "Azure AD", "ServiceNow", "VPN", "Cisco", "Meraki"]:
        tw = draw.textbbox((0, 0), skill, font=mono)[2]
        rounded_rect(draw, (chip_x, y, chip_x + tw + 28, y + 32), 16, (235, 245, 244, 255), (9, 102, 93, 90), 1)
        draw.text((chip_x + 14, y + 7), skill, font=mono, fill=(9, 102, 93, 255))
        chip_x += tw + 38
    boxes["paper"] = paper
    return boxes


def draw_top_cleanup(draw: ImageDraw.ImageDraw) -> None:
    for y in range(0, 130):
        alpha = max(0, int(220 * (1 - (y / 130))))
        draw.rectangle((0, y, OVERLAY_CANVAS[0], y + 1), fill=(28, 18, 10, alpha))


def draw_keyword_chips(draw: ImageDraw.ImageDraw, chips: list[str], x: int, y: int) -> None:
    chip_font = font("segoeuib.ttf", 24)
    for chip in chips:
        bbox = draw.textbbox((0, 0), chip, font=chip_font)
        w = bbox[2] - bbox[0] + 42
        rounded_rect(draw, (x, y, x + w, y + 52), 24, (14, 165, 145, 238), (255, 255, 255, 130), 2)
        draw.text((x + 21, y + 12), chip, font=chip_font, fill=(255, 255, 255, 255))
        y += 66


def draw_small_caption(draw: ImageDraw.ImageDraw, text: str) -> None:
    caption_font = font("segoeuib.ttf", 22)
    lines = wrapped_lines(draw, text, caption_font, 760)
    line_h = 30
    h = line_h * len(lines) + 30
    box = (162, 1590, 918, 1590 + h)
    rounded_rect(draw, box, 18, (7, 11, 18, 150), (255, 255, 255, 55), 1)
    y = box[1] + 16
    for line in lines:
        bbox = draw.textbbox((0, 0), line, font=caption_font)
        draw.text(((1080 - (bbox[2] - bbox[0])) / 2, y), line, font=caption_font, fill=(255, 255, 255, 224))
        y += line_h


def generate_overlays(args: argparse.Namespace) -> None:
    work_dir = Path(args.work_dir).resolve()
    work_dir.mkdir(parents=True, exist_ok=True)
    title_font = font("segoeuib.ttf", 46)
    note_font = font("segoeuib.ttf", 30)
    body_font = font("segoeui.ttf", 25)

    weak_text = "Handled network issues"
    rewrite = "Resolved 40+ weekly network incidents across Cisco switches, VPN access, and firewall changes."

    outputs: list[str] = []
    for index in range(1, 5):
        image = Image.new("RGBA", OVERLAY_CANVAS, (0, 0, 0, 0))
        draw = ImageDraw.Draw(image)
        draw_top_cleanup(draw)
        boxes = draw_resume_base(draw)
        weak = boxes["weak_bullet"]
        paper = boxes["paper"]

        if index >= 2:
            draw.rounded_rectangle(weak, radius=12, outline=(239, 68, 68, 235), width=7)
            draw.line((weak[0] + 18, weak[3] - 18, weak[2] - 18, weak[3] - 18), fill=(239, 68, 68, 235), width=6)
            if index < 4:
                draw.text((weak[0], weak[1] - 44), "too vague", font=note_font, fill=(239, 68, 68, 255))

        if index >= 3:
            draw_keyword_chips(draw, ["Cisco", "VPN", "Firewall", "Incidents"], 108, 1080)
            draw_small_caption(draw, "Use the job's language.")

        if index >= 4:
            cover = (paper[0] + 40, 830, paper[2] - 40, 1114)
            rounded_rect(draw, cover, 18, (255, 255, 255, 248), (20, 27, 38, 72), 2)
            draw.text((cover[0] + 24, cover[1] + 20), "Replace this:", font=note_font, fill=(239, 68, 68, 255))
            draw.text((cover[0] + 24, cover[1] + 64), weak_text, font=body_font, fill=(15, 23, 42, 255))
            draw.line((cover[0] + 24, cover[1] + 84, cover[0] + 350, cover[1] + 84), fill=(239, 68, 68, 230), width=5)
            draw.text((cover[0] + 24, cover[1] + 112), "With this:", font=note_font, fill=(9, 102, 93, 255))
            y = cover[1] + 154
            for line in wrapped_lines(draw, rewrite, body_font, cover[2] - cover[0] - 48):
                draw.text((cover[0] + 24, y), line, font=body_font, fill=(15, 23, 42, 255))
                y += 34
            draw_small_caption(draw, "Now the proof is searchable.")
        elif index == 1:
            draw_small_caption(draw, "One weak line can bury the resume.")
        elif index == 2:
            draw_small_caption(draw, "This tells a recruiter almost nothing.")

        out = work_dir / f"overlay{index:02d}.png"
        image.save(out)
        outputs.append(str(out))

    if args.run_id:
        conn = db()
        get_run(conn, args.run_id)
        metadata = json.loads(get_run(conn, args.run_id)["metadata_json"] or "{}")
        metadata["resumeOverlays"] = outputs
        update_run(conn, args.run_id, metadata_json=json.dumps(metadata))
        log_event(conn, args.run_id, "resume_overlays_generated", {"overlays": outputs})
        conn.commit()

    emit({"status": "OVERLAYS_GENERATED", "overlays": outputs})


def draw_progress_line(draw: ImageDraw.ImageDraw, start: tuple[int, int], end: tuple[int, int], progress: float, fill: tuple[int, int, int, int], width: int) -> None:
    progress = max(0.0, min(1.0, progress))
    x = start[0] + (end[0] - start[0]) * progress
    y = start[1] + (end[1] - start[1]) * progress
    draw.line((start[0], start[1], x, y), fill=fill, width=width)


def draw_progress_rect(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], progress: float, fill: tuple[int, int, int, int], width: int = 6) -> None:
    progress = max(0.0, min(1.0, progress))
    x1, y1, x2, y2 = box
    segments = [
        ((x1, y1), (x2, y1)),
        ((x2, y1), (x2, y2)),
        ((x2, y2), (x1, y2)),
        ((x1, y2), (x1, y1)),
    ]
    remaining = progress * 4
    for start, end in segments:
        if remaining <= 0:
            break
        draw_progress_line(draw, start, end, min(1.0, remaining), fill, width)
        remaining -= 1


def draw_badge(draw: ImageDraw.ImageDraw, text: str, x: int, y: int, fill: tuple[int, int, int, int], text_fill: tuple[int, int, int, int]) -> None:
    badge_font = font("segoeuib.ttf", 23)
    bbox = draw.textbbox((0, 0), text, font=badge_font)
    width = bbox[2] - bbox[0] + 28
    height = bbox[3] - bbox[1] + 18
    rounded_rect(draw, (x, y, x + width, y + height), 14, fill, (255, 255, 255, 80), 1)
    draw.text((x + 14, y + 8), text, font=badge_font, fill=text_fill)


def point_on_rect(box: tuple[int, int, int, int], progress: float) -> tuple[int, int]:
    progress = max(0.0, min(1.0, progress))
    x1, y1, x2, y2 = box
    perimeter = 2 * ((x2 - x1) + (y2 - y1))
    distance = progress * perimeter
    top = x2 - x1
    right = y2 - y1
    bottom = x2 - x1
    if distance <= top:
        return int(x1 + distance), y1
    distance -= top
    if distance <= right:
        return x2, int(y1 + distance)
    distance -= right
    if distance <= bottom:
        return int(x2 - distance), y2
    distance -= bottom
    return x1, int(y2 - min(distance, y2 - y1))


def draw_editor_hand(draw: ImageDraw.ImageDraw, tip: tuple[int, int], marker: tuple[int, int, int, int] = (239, 68, 68, 245)) -> None:
    """Draw a small top-layer editing hand so visible changes happen on the readable resume."""
    tip_x, tip_y = tip
    tail_x = tip_x + 92
    tail_y = tip_y + 78
    skin = (229, 181, 139, 248)
    skin_dark = (180, 122, 89, 210)
    nail = (250, 238, 228, 245)
    shadow = (0, 0, 0, 42)

    # Soft shadow and wrist.
    draw.ellipse((tail_x + 10, tail_y + 42, tail_x + 190, tail_y + 138), fill=shadow)
    rounded_rect(draw, (tail_x + 78, tail_y + 52, tail_x + 178, tail_y + 126), 28, skin, skin_dark, 2)

    # Palm and thumb around the stylus.
    draw.ellipse((tail_x + 36, tail_y + 18, tail_x + 142, tail_y + 102), fill=skin, outline=skin_dark, width=2)
    draw.ellipse((tail_x + 18, tail_y + 42, tail_x + 78, tail_y + 98), fill=skin, outline=skin_dark, width=2)

    # Fingers, intentionally simplified so they read at Shorts scale.
    for offset, length in [(0, 82), (25, 76), (49, 66)]:
        finger_box = (tail_x + 30 + offset, tail_y - 18 + offset // 4, tail_x + 62 + offset, tail_y - 18 + length)
        rounded_rect(draw, finger_box, 15, skin, skin_dark, 2)
        nail_y = finger_box[1] + 6
        draw.ellipse((finger_box[0] + 8, nail_y, finger_box[2] - 8, nail_y + 16), fill=nail)

    # Stylus/marker. The tip lands exactly where the animated edit is happening.
    draw.line((tail_x + 20, tail_y + 26, tip_x, tip_y), fill=(20, 27, 38, 210), width=16)
    draw.line((tail_x + 20, tail_y + 26, tip_x, tip_y), fill=(245, 250, 255, 255), width=10)
    draw.line((tip_x + 3, tip_y + 3, tip_x + 26, tip_y + 26), fill=marker, width=10)
    draw.ellipse((tip_x - 9, tip_y - 9, tip_x + 9, tip_y + 9), fill=marker)


def draw_live_edit_resume_base(draw: ImageDraw.ImageDraw, updated: bool = False, typed_rewrite: str = "") -> dict[str, tuple[int, int, int, int]]:
    paper = (132, 270, 948, 1468)
    shadow = (paper[0] + 16, paper[1] + 18, paper[2] + 16, paper[3] + 18)
    rounded_rect(draw, shadow, 28, (0, 0, 0, 78))
    rounded_rect(draw, (paper[0] - 18, paper[1] - 22, paper[2] + 18, paper[3] + 22), 34, (18, 24, 31, 220), (255, 255, 255, 48), 2)
    rounded_rect(draw, paper, 18, (252, 252, 248, 250), (20, 27, 38, 70), 2)

    title = font("segoeuib.ttf", 36)
    subtitle = font("segoeui.ttf", 17)
    section = font("segoeuib.ttf", 16)
    role = font("segoeuib.ttf", 20)
    body = font("segoeui.ttf", 18)
    small = font("segoeui.ttf", 15)
    tiny = font("segoeui.ttf", 14)
    mono = font("consola.ttf", 14)

    x = paper[0] + 56
    y = paper[1] + 44
    draw.text((x, y), "MAYA RIVERA", font=title, fill=(15, 23, 42, 255))
    draw.text((x, y + 44), "Customer Success Manager  |  Denver, CO  |  maya.r@example.com  |  linkedin.com/in/mayarivera", font=subtitle, fill=(72, 84, 104, 255))
    draw.line((x, y + 78, paper[2] - 56, y + 78), fill=(20, 27, 38, 80), width=2)

    y += 105
    draw.text((x, y), "PROFESSIONAL SUMMARY", font=section, fill=(9, 102, 93, 255))
    y += 27
    summary = "Customer success manager with 5+ years supporting B2B SaaS onboarding, renewal risk reviews, user adoption, and executive account updates."
    for line in wrapped_lines(draw, summary, small, paper[2] - 112 - x):
        draw.text((x, y), line, font=small, fill=(31, 41, 55, 255))
        y += 22

    y += 18
    draw.text((x, y), "CORE SKILLS", font=section, fill=(9, 102, 93, 255))
    y += 28
    skill_rows = [
        ("Customer Success", "onboarding, renewals, QBRs, adoption plans, churn-risk reviews"),
        ("Tools", "Salesforce, Gainsight, Zendesk, Looker, Slack, Google Workspace"),
        ("Metrics", "NRR, GRR, health scores, product usage, expansion pipeline, SLA follow-up"),
        ("Industries", "B2B SaaS, education technology, healthcare operations"),
    ]
    for label, value in skill_rows:
        draw.text((x, y), label + ":", font=font("segoeuib.ttf", 14), fill=(15, 23, 42, 255))
        draw.text((x + 136, y), value, font=tiny, fill=(55, 65, 81, 255))
        y += 22

    y += 18
    draw.text((x, y), "EXPERIENCE", font=section, fill=(9, 102, 93, 255))
    y += 30
    draw.text((x, y), "Customer Success Manager  |  Northline Software", font=role, fill=(15, 23, 42, 255))
    draw.text((paper[2] - 230, y + 3), "2022 - Present", font=small, fill=(72, 84, 104, 255))
    y += 36

    weak_bullet = "Helped customers with onboarding and renewals."
    strong_bullet = "Led onboarding for 42 B2B accounts, flagged churn risk in Gainsight, and protected $1.2M in annual renewals."
    bullets = [
        strong_bullet if updated else weak_bullet,
        "Managed a book of 68 SMB and mid-market accounts with weekly usage reviews, renewal notes, and escalation follow-up.",
        "Built onboarding checklists that reduced first-value time from 21 days to 14 days across new customer cohorts.",
        "Partnered with sales on expansion handoffs and documented customer health trends in Salesforce.",
        "Hosted monthly QBRs for strategic accounts, translating product usage data into clear next-step plans.",
    ]
    boxes: dict[str, tuple[int, int, int, int]] = {}
    for idx, bullet in enumerate(bullets):
        bullet_y = y
        draw.text((x + 4, bullet_y + 2), u"\u2022", font=body, fill=(15, 23, 42, 255))
        line_x = x + 34
        if idx == 0 and typed_rewrite:
            rounded_rect(draw, (line_x - 8, bullet_y - 8, paper[2] - 62, bullet_y + 72), 12, (255, 255, 255, 250), (20, 27, 38, 45), 1)
            typed_lines = wrapped_lines(draw, typed_rewrite, body, paper[2] - 92 - line_x)
            for line_index, line in enumerate(typed_lines[:3]):
                draw.text((line_x, bullet_y + line_index * 25), line, font=body, fill=(15, 23, 42, 255))
            box_h = max(58, len(typed_lines[:3]) * 25)
            boxes["weak_bullet"] = (line_x - 10, bullet_y - 8, paper[2] - 66, bullet_y + 62)
            boxes["rewrite_bullet"] = (line_x - 10, bullet_y - 8, paper[2] - 66, bullet_y + box_h + 8)
            y += box_h + 20
            continue
        lines = wrapped_lines(draw, bullet, body, paper[2] - 92 - line_x)
        for line_index, line in enumerate(lines):
            draw.text((line_x, bullet_y + line_index * 25), line, font=body, fill=(15, 23, 42, 255))
        box_h = max(30, len(lines) * 25)
        if idx == 0:
            boxes["weak_bullet"] = (line_x - 10, bullet_y - 8, paper[2] - 66, bullet_y + box_h + 6)
        y += box_h + 15

    y += 12
    draw.text((x, y), "Customer Success Associate  |  Brightpath Learning", font=role, fill=(15, 23, 42, 255))
    draw.text((paper[2] - 230, y + 3), "2020 - 2022", font=small, fill=(72, 84, 104, 255))
    y += 34
    earlier_bullets = [
        "Answered implementation questions for 90+ school-district customers using Zendesk and product usage reports.",
        "Created renewal briefing notes for account executives before district budget meetings.",
    ]
    for bullet in earlier_bullets:
        draw.text((x + 4, y + 2), u"\u2022", font=body, fill=(15, 23, 42, 255))
        for line in wrapped_lines(draw, bullet, small, paper[2] - 145 - x):
            draw.text((x + 34, y), line, font=small, fill=(31, 41, 55, 255))
            y += 22
        y += 8

    y += 14
    draw.text((x, y), "PROJECTS", font=section, fill=(9, 102, 93, 255))
    y += 28
    projects = [
        "Churn-risk dashboard: tagged renewal accounts by product usage, support volume, and executive sponsor engagement.",
        "Onboarding library: rewrote customer kickoff templates and reduced repeat support questions during launch week.",
    ]
    for project in projects:
        draw.text((x + 4, y + 2), u"\u2022", font=body, fill=(15, 23, 42, 255))
        for line in wrapped_lines(draw, project, small, paper[2] - 145 - x):
            draw.text((x + 34, y), line, font=small, fill=(31, 41, 55, 255))
            y += 22
        y += 8

    y += 8
    draw.text((x, y), "EDUCATION", font=section, fill=(9, 102, 93, 255))
    y += 28
    draw.text((x, y), "B.A. Communication, University of Colorado  |  Certified Customer Success Manager", font=small, fill=(31, 41, 55, 255))

    y += 38
    chip_x = paper[0] + 56
    for skill in ["Salesforce", "Gainsight", "Renewals", "Onboarding", "Churn Risk"]:
        tw = draw.textbbox((0, 0), skill, font=mono)[2]
        rounded_rect(draw, (chip_x, y, chip_x + tw + 28, y + 32), 16, (235, 245, 244, 255), (9, 102, 93, 90), 1)
        draw.text((chip_x + 14, y + 7), skill, font=mono, fill=(9, 102, 93, 255))
        chip_x += tw + 38
        if chip_x > paper[2] - 150:
            chip_x = paper[0] + 56
            y += 38

    boxes["paper"] = paper
    boxes["strong_bullet_text"] = (0, 0, 0, 0)
    return boxes


def draw_live_edit_frame(draw: ImageDraw.ImageDraw, stage: int, progress: float) -> None:
    draw_top_cleanup(draw)
    rewrite = "Led onboarding for 42 B2B accounts, flagged churn risk in Gainsight, and protected $1.2M in annual renewals."
    typed_rewrite = ""
    updated = stage >= 4
    if stage == 3:
        type_progress = max(0.0, min(1.0, (progress - 0.28) / 0.62))
        typed_rewrite = rewrite[: int(len(rewrite) * type_progress)]
    boxes = draw_live_edit_resume_base(draw, updated=updated, typed_rewrite=typed_rewrite)
    weak = boxes["weak_bullet"]

    small_note = font("segoeuib.ttf", 23)
    red = (239, 68, 68, 235)
    green = (14, 165, 145, 235)

    if stage == 1:
        draw_small_caption(draw, "This resume looks real. One line is still doing nothing.")
    elif stage == 2:
        draw_progress_rect(draw, weak, progress, red, width=7)
        draw_editor_hand(draw, point_on_rect(weak, progress), red)
        if progress > 0.35:
            draw_badge(draw, "too vague", weak[2] - 158, weak[1] - 42, (127, 29, 29, 232), (255, 255, 255, 255))
        if progress > 0.65:
            draw_small_caption(draw, "Circle the claim with no proof.")
    elif stage == 3:
        draw.rounded_rectangle(weak, radius=12, outline=red, width=6)
        strike_progress = min(1.0, progress * 1.8)
        strike_start = (weak[0] + 18, weak[3] - 18)
        strike_end = (weak[2] - 18, weak[3] - 18)
        draw_progress_line(draw, strike_start, strike_end, strike_progress, red, 6)
        draw_badge(draw, "delete vague", weak[2] - 198, weak[1] - 42, (127, 29, 29, 232), (255, 255, 255, 255))
        if progress < 0.32:
            hand_tip = (
                int(strike_start[0] + (strike_end[0] - strike_start[0]) * strike_progress),
                strike_start[1],
            )
            draw_editor_hand(draw, hand_tip, red)
        else:
            type_progress = max(0.0, min(1.0, (progress - 0.28) / 0.62))
            hand_tip = (
                min(weak[2] - 160, weak[0] + 24 + int((weak[2] - weak[0] - 210) * type_progress)),
                weak[1] + 55,
            )
            draw.line((hand_tip[0], hand_tip[1] - 24, hand_tip[0], hand_tip[1] + 16), fill=(9, 102, 93, 230), width=4)
            draw_editor_hand(draw, hand_tip, green)
        if progress > 0.25:
            draw.text((weak[0], weak[3] + 16), "typing proof...", font=small_note, fill=(9, 102, 93, 255))
        draw_small_caption(draw, "Now the edit is happening on the page.")
    else:
        highlight = boxes["weak_bullet"]
        draw.rounded_rectangle((highlight[0], highlight[1], highlight[2], highlight[3] + 26), radius=14, outline=(14, 165, 145, 210), width=5)
        draw_keyword_chips(draw, ["Salesforce", "Gainsight", "Renewals", "Churn Risk"], 96, 1080)
        draw_badge(draw, "fixed with proof", highlight[2] - 220, highlight[1] - 42, (6, 95, 70, 232), (255, 255, 255, 255))
        draw_editor_hand(draw, (highlight[2] - 36, highlight[3] + 18), green)
        draw_small_caption(draw, "Upload it to Signal before you apply.")


def voice_duration_sec(work_dir: Path, voice_name: str, fallback: float) -> float:
    voice_path = work_dir / voice_name
    if not voice_path.exists():
        return fallback
    try:
        ffprobe = find_exe("ffprobe")
        proc = subprocess.run(
            [ffprobe, "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(voice_path)],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
        )
        return max(0.4, float(proc.stdout.strip()))
    except Exception:
        return fallback


def generate_live_edit_overlays(args: argparse.Namespace) -> None:
    work_dir = Path(args.work_dir).resolve()
    work_dir.mkdir(parents=True, exist_ok=True)
    fps = 30
    defaults = [4.6, 5.4, 8.1, 5.4]
    voices = ["vo_hook.mp3", "vo_search.mp3", "vo_demo.mp3", "vo_cta.mp3"]
    outputs: list[str] = []

    for stage, (voice_name, fallback) in enumerate(zip(voices, defaults), start=1):
        duration = voice_duration_sec(work_dir, voice_name, fallback)
        frame_count = max(2, int(duration * fps))
        frame_dir = work_dir / f"overlay{stage:02d}_frames"
        if frame_dir.exists():
            shutil.rmtree(frame_dir)
        frame_dir.mkdir(parents=True, exist_ok=True)
        for frame in range(frame_count):
            progress = 1.0 if frame_count <= 1 else frame / (frame_count - 1)
            image = Image.new("RGBA", OVERLAY_CANVAS, (0, 0, 0, 0))
            draw = ImageDraw.Draw(image)
            draw_live_edit_frame(draw, stage, progress)
            image.save(frame_dir / f"{frame:04d}.png")
        outputs.append(str(frame_dir))

    if args.run_id:
        conn = db()
        get_run(conn, args.run_id)
        metadata = json.loads(get_run(conn, args.run_id)["metadata_json"] or "{}")
        metadata["liveEditOverlayFrames"] = outputs
        update_run(conn, args.run_id, metadata_json=json.dumps(metadata))
        log_event(conn, args.run_id, "live_edit_overlays_generated", {"frameDirs": outputs})
        conn.commit()

    emit({"status": "LIVE_EDIT_OVERLAYS_GENERATED", "frameDirs": outputs})


def find_exe(name: str) -> str:
    found = shutil.which(name)
    if found:
        return found
    winget_root = Path(os.environ.get("LOCALAPPDATA", "")) / "Microsoft" / "WinGet" / "Packages"
    if winget_root.exists():
        matches = sorted(winget_root.rglob(f"{name}.exe"))
        if matches:
            return str(matches[-1])
    raise SystemExit(f"Could not find {name}. Install ffmpeg/ffprobe or add it to PATH.")


def assemble(args: argparse.Namespace) -> None:
    if not ASSEMBLE_PS1.exists():
        raise SystemExit(f"Missing assembler: {ASSEMBLE_PS1}")
    work_dir = Path(args.work_dir).resolve()
    out = args.out
    command = [
        "powershell",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        str(ASSEMBLE_PS1),
        "-WorkDir",
        str(work_dir),
        "-Out",
        out,
    ]
    if getattr(args, "background_clip", None):
        command.extend(["-BackgroundClip", str(Path(args.background_clip).resolve())])
    subprocess.run(command, cwd=str(ROOT), check=True)
    video_path = work_dir / out
    if args.run_id:
        conn = db()
        get_run(conn, args.run_id)
        update_run(conn, args.run_id, status="RENDERED", video_path=str(video_path))
        log_event(conn, args.run_id, "rendered", {"videoPath": str(video_path), "assembler": str(ASSEMBLE_PS1)})
        conn.commit()
    emit({"status": "RENDERED", "video": str(video_path)})


def ffprobe_json(video: Path) -> dict[str, Any]:
    ffprobe = find_exe("ffprobe")
    proc = subprocess.run(
        [
            ffprobe,
            "-v",
            "error",
            "-show_streams",
            "-show_format",
            "-of",
            "json",
            str(video),
        ],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    return json.loads(proc.stdout)


def frame_rate(stream: dict[str, Any]) -> float:
    raw = stream.get("avg_frame_rate") or stream.get("r_frame_rate") or "0/1"
    if "/" in raw:
        num, den = raw.split("/", 1)
        return float(num) / float(den or 1)
    return float(raw)


def qa(args: argparse.Namespace) -> None:
    video = Path(args.video).resolve()
    if not video.exists():
        raise SystemExit(f"Video not found: {video}")
    data = ffprobe_json(video)
    streams = data.get("streams", [])
    video_stream = next((stream for stream in streams if stream.get("codec_type") == "video"), None)
    audio_stream = next((stream for stream in streams if stream.get("codec_type") == "audio"), None)
    blockers: list[str] = []
    if not video_stream:
        blockers.append("missing video stream")
    if not audio_stream:
        blockers.append("missing audio stream")
    if video_stream:
        fps = frame_rate(video_stream)
        if video_stream.get("codec_name") != "h264":
            blockers.append(f"video codec is {video_stream.get('codec_name')}, expected h264")
        if int(video_stream.get("width", 0)) != 1080 or int(video_stream.get("height", 0)) != 1920:
            blockers.append(f"video is {video_stream.get('width')}x{video_stream.get('height')}, expected 1080x1920")
        if abs(fps - 30) > 0.15:
            blockers.append(f"video is {fps:.3f}fps, expected 30fps")
    if audio_stream:
        if audio_stream.get("codec_name") != "aac":
            blockers.append(f"audio codec is {audio_stream.get('codec_name')}, expected aac")
        sample_rate = int(audio_stream.get("sample_rate", 0) or 0)
        if sample_rate not in {44100, 48000}:
            blockers.append(f"audio sample rate is {sample_rate}, expected 44100 or 48000")
    duration = float(data.get("format", {}).get("duration") or 0)
    if duration < 5:
        blockers.append(f"duration is {duration:.2f}s")

    report = {
        "video": str(video),
        "passed": not blockers,
        "blockers": blockers,
        "durationSec": round(duration, 3),
        "videoCodec": video_stream.get("codec_name") if video_stream else None,
        "width": video_stream.get("width") if video_stream else None,
        "height": video_stream.get("height") if video_stream else None,
        "fps": round(frame_rate(video_stream), 3) if video_stream else None,
        "audioCodec": audio_stream.get("codec_name") if audio_stream else None,
        "sampleRate": audio_stream.get("sample_rate") if audio_stream else None,
        "fileBytes": video.stat().st_size,
        "checkedAt": utc_now(),
    }

    if args.write:
        out = video.with_suffix(video.suffix + ".qa.json")
        out.write_text(json.dumps(report, indent=2), encoding="utf-8")
        report["reportPath"] = str(out)

    if args.run_id:
        conn = db()
        get_run(conn, args.run_id)
        status = "AWAITING_CODEX_APPROVAL" if report["passed"] else "FAILED"
        update_run(conn, args.run_id, status=status, video_path=str(video), qa_json=json.dumps(report))
        log_event(conn, args.run_id, "qa", report)
        conn.commit()
        report["runId"] = args.run_id
        report["status"] = status

    emit(report)
    if blockers:
        raise SystemExit(1)


def review(args: argparse.Namespace) -> None:
    conn = db()
    row = get_run(conn, args.run_id)
    metadata = json.loads(row["metadata_json"] or "{}")
    qa_report = json.loads(row["qa_json"] or "{}")
    video_path = row["video_path"]
    if not video_path:
        raise SystemExit("No video_path stored for this run yet.")
    video = Path(video_path)
    if not video.exists():
        raise SystemExit(f"Stored video path does not exist: {video}")
    mobile_url = f"http://{args.host}:{args.port}/{video.name}" if args.host else None
    packet = {
        "runId": row["id"],
        "status": row["status"],
        "title": row["title"],
        "videoPath": str(video),
        "mobileUrl": mobile_url,
        "platforms": metadata.get("platforms", ["youtube_shorts", "tiktok", "instagram_reels"]),
        "cta": "Run the free Signal score before you apply.",
        "landingUrl": row["landing_url"],
        "approvalPhrase": metadata.get("approvalPhrase", f"APPROVE POST {row['id']}"),
        "qa": qa_report,
        "publishBlocked": row["status"] != "APPROVED",
    }
    emit(packet)


def approve(args: argparse.Namespace) -> None:
    expected = f"APPROVE POST {args.run_id}"
    if args.phrase.strip() != expected:
        raise SystemExit(f"Approval phrase mismatch. Expected exactly: {expected}")
    conn = db()
    row = get_run(conn, args.run_id)
    if row["status"] != "AWAITING_CODEX_APPROVAL":
        raise SystemExit(f"Run must be AWAITING_CODEX_APPROVAL before approval. Current status: {row['status']}")
    update_run(conn, args.run_id, status="APPROVED")
    log_event(conn, args.run_id, "approved", {"reviewer": "codex-chat", "phrase": args.phrase})
    conn.commit()
    emit({"runId": args.run_id, "status": "APPROVED", "publishStillRequiresPublisherCommand": True})


def mark_status(args: argparse.Namespace) -> None:
    conn = db()
    get_run(conn, args.run_id)
    update_run(conn, args.run_id, status=args.status)
    log_event(conn, args.run_id, "status_changed", {"status": args.status, "reason": args.reason or ""})
    conn.commit()
    emit({"runId": args.run_id, "status": args.status})


def show_state(args: argparse.Namespace) -> None:
    conn = db()
    if args.run_id:
        row = dict(get_run(conn, args.run_id))
        row["metadata_json"] = json.loads(row["metadata_json"] or "{}")
        row["qa_json"] = json.loads(row["qa_json"] or "{}")
        emit(row)
        return
    rows = [dict(row) for row in conn.execute("SELECT id, topic, title, status, video_path, updated_at FROM video_runs ORDER BY updated_at DESC LIMIT ?", (args.limit,))]
    emit({"runs": rows})


def create_batch(args: argparse.Namespace) -> None:
    topics: list[str] = []
    if args.topics:
        topics.extend(args.topics)
    if args.topics_file:
        topics.extend(
            line.strip()
            for line in Path(args.topics_file).read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.strip().startswith("#")
        )
    if not topics:
        raise SystemExit("Provide --topics or --topics-file")

    created: list[dict[str, Any]] = []
    for topic in topics:
        ns = argparse.Namespace(topic=topic, title=None, landing_url=args.landing_url)
        before = set(path.name for path in RUNS_DIR.glob("*")) if RUNS_DIR.exists() else set()
        create_run(ns)
        after = set(path.name for path in RUNS_DIR.glob("*"))
        new_ids = sorted(after - before)
        if new_ids:
            created.append({"runId": new_ids[-1], "topic": topic, "folder": str(run_folder(new_ids[-1]))})
    emit({"created": created, "count": len(created)})


def run_stage_command(command: list[str]) -> dict[str, Any]:
    proc = subprocess.run(command, cwd=str(ROOT), text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return {
        "command": command,
        "returncode": proc.returncode,
        "stdout": proc.stdout[-2000:],
        "stderr": proc.stderr[-2000:],
    }


def batch_process(args: argparse.Namespace) -> None:
    run_ids = args.runs or []
    if args.runs_file:
        run_ids.extend(
            line.strip()
            for line in Path(args.runs_file).read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.strip().startswith("#")
        )
    if not run_ids:
        conn = db()
        run_ids = [
            row["id"]
            for row in conn.execute(
                "SELECT id FROM video_runs WHERE status IN ('QUEUED', 'RESEARCHED', 'SCRIPTED', 'VOICED', 'VIDEO_GENERATED') ORDER BY created_at DESC LIMIT ?",
                (args.limit,),
            )
        ]
    if not run_ids:
        raise SystemExit("No runs found to process.")

    commands: list[list[str]] = []
    python = sys.executable
    for run_id in run_ids:
        folder = run_folder(run_id)
        if args.stage in {"voice", "all"}:
            for text_file in sorted(folder.glob("vo*.txt")):
                out = folder / f"{text_file.stem}.mp3"
                if args.force or not out.exists():
                    commands.append(
                        [
                            python,
                            str(Path(__file__).resolve()),
                            "voice",
                            "--text-file",
                            str(text_file),
                            "--out",
                            str(out),
                            "--run-id",
                            run_id,
                        ]
                    )
        if args.stage in {"veo", "all"}:
            for shot_file in sorted(folder.glob("shot*.txt")):
                out = folder / f"{shot_file.stem}.mp4"
                if args.force or not out.exists():
                    commands.append(
                        [
                            python,
                            str(Path(__file__).resolve()),
                            "veo",
                            "--text-file",
                            str(shot_file),
                            "--out",
                            str(out),
                            "--run-id",
                            run_id,
                        ]
                        + (["--model", args.model] if args.model else [])
                    )
    if not commands:
        emit({"status": "noop", "runs": run_ids, "stage": args.stage})
        return
    if args.dry_run:
        emit({"dryRun": True, "commands": commands})
        return

    results: list[dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=max(1, args.max_workers)) as pool:
        futures = [pool.submit(run_stage_command, command) for command in commands]
        for future in as_completed(futures):
            results.append(future.result())
    failed = [result for result in results if result["returncode"] != 0]
    emit({"processed": len(results), "failed": len(failed), "results": results})
    if failed:
        raise SystemExit(1)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Signal Growth Engine pipeline")
    sub = parser.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init-run", help="Create a durable queued video run")
    init.add_argument("--topic", required=True)
    init.add_argument("--title")
    init.add_argument("--landing-url")
    init.set_defaults(func=create_run)

    resolve = sub.add_parser("resolve-abby", help="Resolve the Abby ElevenLabs voice ID")
    resolve.add_argument("--strict", action="store_true")
    resolve.set_defaults(func=resolve_abby)

    voice = sub.add_parser("voice", help="Generate Abby voiceover with timestamps")
    voice.add_argument("--text")
    voice.add_argument("--text-file")
    voice.add_argument("--out", required=True)
    voice.add_argument("--run-id")
    voice.add_argument("--voice-id")
    voice.add_argument("--model-id")
    voice.add_argument("--stability", type=float, default=0.46)
    voice.add_argument("--similarity", type=float, default=0.82)
    voice.add_argument("--style", type=float, default=0.32)
    voice.set_defaults(func=generate_voice)

    veo = sub.add_parser("veo", help="Generate a Veo clip through the Gemini API")
    veo.add_argument("--text")
    veo.add_argument("--text-file")
    veo.add_argument("--out", required=True)
    veo.add_argument("--run-id")
    veo.add_argument("--model")
    veo.add_argument("--aspect-ratio", default="9:16")
    veo.add_argument("--poll-sec", type=int, default=10)
    veo.add_argument("--timeout-sec", type=int, default=900)
    veo.add_argument("--dry-run", action="store_true")
    veo.set_defaults(func=generate_veo)

    overlays = sub.add_parser("overlays", help="Generate deterministic readable resume overlays for Veo footage")
    overlays.add_argument("--work-dir", required=True)
    overlays.add_argument("--run-id")
    overlays.set_defaults(func=generate_overlays)

    live_edit = sub.add_parser("live-edit-overlays", help="Generate animated resume edit overlay frames for Veo footage")
    live_edit.add_argument("--work-dir", required=True)
    live_edit.add_argument("--run-id")
    live_edit.set_defaults(func=generate_live_edit_overlays)

    assm = sub.add_parser("assemble", help="Run the sync-safe ffmpeg assembly script")
    assm.add_argument("--work-dir", default=str(Path.home() / "Downloads"))
    assm.add_argument("--out", default="signal_ad_final_pipeline.mp4")
    assm.add_argument("--run-id")
    assm.add_argument("--background-clip")
    assm.set_defaults(func=assemble)

    quality = sub.add_parser("qa", help="Validate render technical requirements")
    quality.add_argument("--video", required=True)
    quality.add_argument("--run-id")
    quality.add_argument("--write", action="store_true")
    quality.set_defaults(func=qa)

    review_cmd = sub.add_parser("review", help="Print Codex approval packet")
    review_cmd.add_argument("--run-id", required=True)
    review_cmd.add_argument("--host", default="192.168.2.10")
    review_cmd.add_argument("--port", default="8770")
    review_cmd.set_defaults(func=review)

    approve_cmd = sub.add_parser("approve", help="Mark a reviewed video approved")
    approve_cmd.add_argument("--run-id", required=True)
    approve_cmd.add_argument("--phrase", required=True)
    approve_cmd.set_defaults(func=approve)

    status_cmd = sub.add_parser("status", help="Set a status manually for review/revision bookkeeping")
    status_cmd.add_argument("--run-id", required=True)
    status_cmd.add_argument("--status", required=True, choices=sorted(STATUS_ORDER))
    status_cmd.add_argument("--reason")
    status_cmd.set_defaults(func=mark_status)

    state = sub.add_parser("state", help="Show recent runs or one run")
    state.add_argument("--run-id")
    state.add_argument("--limit", type=int, default=10)
    state.set_defaults(func=show_state)

    batch_init = sub.add_parser("batch-init", help="Create several queued runs from topics")
    batch_init.add_argument("--topics", nargs="*")
    batch_init.add_argument("--topics-file")
    batch_init.add_argument("--landing-url")
    batch_init.set_defaults(func=create_batch)

    batch = sub.add_parser("batch-process", help="Process ready VO/Veo files for multiple runs concurrently")
    batch.add_argument("--runs", nargs="*")
    batch.add_argument("--runs-file")
    batch.add_argument("--stage", choices=["voice", "veo", "all"], default="all")
    batch.add_argument("--max-workers", type=int, default=3)
    batch.add_argument("--limit", type=int, default=3)
    batch.add_argument("--model")
    batch.add_argument("--force", action="store_true")
    batch.add_argument("--dry-run", action="store_true")
    batch.set_defaults(func=batch_process)

    return parser


def main() -> None:
    load_env()
    args = build_parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
